Repository alddeul-hankki/Backend, pull requests merged in 2025-08, with the labels that each got.

#5 [AH-8] erd 초안 작성
  src/main/java/com/alddeul/solsolhanhankki/SolsolhanhankkiApplication.java
  src/main/java/com/alddeul/solsolhanhankki/campus/model/entity/PickupZone.java
  src/main/java/com/alddeul/solsolhanhankki/common/jpa/base/entity/AbstractBaseEntity.java
  src/main/java/com/alddeul/solsolhanhankki/common/jpa/base/entity/BaseIdentityEntity.java
  src/main/java/com/alddeul/solsolhanhankki/common/jpa/base/entity/BaseSeqEntity.java
  src/main/java/com/alddeul/solsolhanhankki/common/jpa/base/entity/BaseTimeEntity.java
  src/main/java/com/alddeul/solsolhanhankki/order/model/entity/GroupOrder.java
  src/main/java/com/alddeul/solsolhanhankki/order/model/entity/GroupOrderItem.java
  src/main/java/com/alddeul/solsolhanhankki/order/model/entity/GroupOrderMember.java
  src/main/java/com/alddeul/solsolhanhankki/store/model/entity/MenuItem.java
  src/main/java/com/alddeul/solsolhanhankki/store/model/entity/Restaurant.java
  src/main/java/com/alddeul/solsolhanhankki/user/model/entity/SolUser.java
  src/main/java/com/alddeul/solsolhanhankki/wallet/model/entity/PayMoneyWallet.java
  src/main/java/com/alddeul/solsolhanhankki/wallet/model/entity/PaymentIntent.java
  src/main/java/com/alddeul/solsolhanhankki/wallet/model/entity/WalletHold.java
  src/main/java/com/alddeul/solsolhanhankki/wallet/model/entity/WalletLedger.java
Labels: enhancement, backend

#19 [AH-22] 헤이영 서버 분리
  heyyoung/.gitattributes
  heyyoung/.gitignore
  heyyoung/build.gradle
  heyyoung/gradle/wrapper/gradle-wrapper.jar
  heyyoung/gradle/wrapper/gradle-wrapper.properties
  heyyoung/gradlew
  heyyoung/gradlew.bat
  heyyoung/settings.gradle
  heyyoung/src/main/java/com/alddeul/heyyoung/HeyyoungApplication.java
  heyyoung/src/main/java/com/alddeul/heyyoung/common/api/external/dto/ErrorCode.java
  heyyoung/src/main/java/com/alddeul/heyyoung/common/api/external/dto/ErrorResponse.java
  heyyoung/src/main/java/com/alddeul/heyyoung/common/api/external/dto/FinanceApiResponse.java
  heyyoung/src/main/java/com/alddeul/heyyoung/common/api/external/dto/RequestHeader.java
  heyyoung/src/main/java/com/alddeul/heyyoung/common/api/external/dto/ResponseHeader.java
  heyyoung/src/main/java/com/alddeul/heyyoung/common/api/external/utils/WebClientHelper.java
  heyyoung/src/main/java/com/alddeul/heyyoung/common/api/response/ApiResponse.java
  heyyoung/src/main/java/com/alddeul/heyyoung/common/api/response/ResponseCode.java
  heyyoung/src/main/java/com/alddeul/heyyoung/common/config/WebClientConfig.java
  heyyoung/src/main/java/com/alddeul/heyyoung/common/jpa/base/entity/AbstractBaseEntity.java
  heyyoung/src/main/java/com/alddeul/heyyoung/common/jpa/base/entity/BaseIdentityEntity.java
  heyyoung/src/main/java/com/alddeul/heyyoung/common/jpa/base/entity/BaseSeqEntity.java
  heyyoung/src/main/java/com/alddeul/heyyoung/common/jpa/base/entity/BaseTimeEntity.java
  heyyoung/src/main/java/com/alddeul/heyyoung/domain/account/external/auth/FinanceAccountAuthClient.java
  heyyoung/src/main/java/com/alddeul/heyyoung/domain/account/external/auth/dto/CheckAuthCodeRequest.java
  heyyoung/src/main/java/com/alddeul/heyyoung/domain/account/external/auth/dto/CheckAuthCodeResponse.java
  heyyoung/src/main/java/com/alddeul/heyyoung/domain/account/external/auth/dto/OneCentTransferRequest.java
  heyyoung/src/main/java/com/alddeul/heyyoung/domain/account/external/auth/dto/OneCentTransferResponse.java
  heyyoung/src/main/java/com/alddeul/heyyoung/domain/account/external/deposit/FinanceAccountClient.java
  heyyoung/src/main/java/com/alddeul/heyyoung/domain/account/external/deposit/dto/CreateAccountRequest.java
  heyyoung/src/main/java/com/alddeul/heyyoung/domain/account/external/deposit/dto/CreateAccountResponse.java
  heyyoung/src/main/java/com/alddeul/heyyoung/domain/account/external/deposit/dto/InquireAccountHistoryRequest.java
  heyyoung/src/main/java/com/alddeul/heyyoung/domain/account/external/deposit/dto/InquireAccountHistoryResponse.java
  heyyoung/src/main/java/com/alddeul/heyyoung/domain/account/external/deposit/dto/InquireAccountListRequest.java
  heyyoung/src/main/java/com/alddeul/heyyoung/domain/account/external/deposit/dto/InquireAccountListResponse.java
  heyyoung/src/main/java/com/alddeul/heyyoung/domain/user/application/UserAccountService.java
  heyyoung/src/main/java/com/alddeul/heyyoung/domain/user/application/UserFacade.java
  heyyoung/src/main/java/com/alddeul/heyyoung/domain/user/application/UserService.java
  heyyoung/src/main/java/com/alddeul/heyyoung/domain/user/external/FinanceUserApiClient.java
  heyyoung/src/main/java/com/alddeul/heyyoung/domain/user/external/dto/FinanceUserRequest.java
  heyyoung/src/main/java/com/alddeul/heyyoung/domain/user/external/dto/FinanceUserResponse.java
  heyyoung/src/main/java/com/alddeul/heyyoung/domain/user/model/entity/SolUser.java
  heyyoung/src/main/java/com/alddeul/heyyoung/domain/user/model/repository/UserRepository.java
  heyyoung/src/main/java/com/alddeul/heyyoung/domain/user/presentation/UserController.java
  heyyoung/src/main/java/com/alddeul/heyyoung/domain/user/presentation/request/UserRequest.java
  heyyoung/src/main/java/com/alddeul/heyyoung/domain/user/presentation/response/UserResponse.java
  heyyoung/src/main/resources/application.yml
  heyyoung/src/test/java/com/alddeul/heyyoung/HeyyoungApplicationTests.java
Labels: backend

#24 [AH-12] 쏠쏠한 한끼 UI 구현을 위한 API 구현
  ddangyo/src/main/java/com/alddle/ddangyo/config/WebConfig.java
  ddangyo/src/main/java/com/alddle/ddangyo/restaurant/controller/RestaurantController.java
  ddangyo/src/main/java/com/alddle/ddangyo/restaurant/model/dto/MenuDetailRequest.java
  ddangyo/src/main/java/com/alddle/ddangyo/restaurant/model/dto/MenuDetailResponse.java
  ddangyo/src/main/java/com/alddle/ddangyo/restaurant/model/dto/RestaurantDetailRequest.java
  ddangyo/src/main/java/com/alddle/ddangyo/restaurant/model/dto/RestaurantDetailResponse.java
  ddangyo/src/main/java/com/alddle/ddangyo/restaurant/model/dto/RestaurantInfoRequest.java
  ddangyo/src/main/java/com/alddle/ddangyo/restaurant/model/dto/RestaurantInfoResponse.java
  ddangyo/src/main/java/com/alddle/ddangyo/restaurant/model/dto/RestaurantListRequest.java
  ddangyo/src/main/java/com/alddle/ddangyo/restaurant/model/dto/RestaurantSummaryResponse.java
  ddangyo/src/main/java/com/alddle/ddangyo/restaurant/model/entity/Menu.java
  ddangyo/src/main/java/com/alddle/ddangyo/restaurant/model/entity/MenuDetail.java
  ddangyo/src/main/java/com/alddle/ddangyo/restaurant/model/entity/Restaurant.java
  ddangyo/src/main/java/com/alddle/ddangyo/restaurant/model/entity/RestaurantInfo.java
  ddangyo/src/main/java/com/alddle/ddangyo/restaurant/model/repository/MenuDetailRepository.java
  ddangyo/src/main/java/com/alddle/ddangyo/restaurant/model/repository/MenuRepository.java
  ddangyo/src/main/java/com/alddle/ddangyo/restaurant/model/repository/RestaurantInfoRepository.java
  ddangyo/src/main/java/com/alddle/ddangyo/restaurant/model/repository/RestaurantRepository.java
  ddangyo/src/main/java/com/alddle/ddangyo/restaurant/service/RestaurantService.java
Labels: jira, backend

#36 [AH-27] 깃헙 액션 자동 배포 워크플로 작성
  .github/workflows/deploy-heyyoung.yml
  .github/workflows/deploy-solsol.yml
  heyyoung/Dockerfile
  heyyoung/src/main/resources/application.yml
  solsolhanhankki/.gitignore
  solsolhanhankki/Dockerfile
  solsolhanhankki/gradle/wrapper/gradle-wrapper.jar
  solsolhanhankki/src/main/resources/application-dev.yml
  solsolhanhankki/src/main/resources/application.yml
Labels: backend

#49 [AH-41] notification url 추가
  solsolhanhankki/src/main/java/com/alddeul/solsolhanhankki/notification/controller/TestNotificationController.java
  solsolhanhankki/src/main/java/com/alddeul/solsolhanhankki/notification/dto/NotificationEventDto.java
  solsolhanhankki/src/main/java/com/alddeul/solsolhanhankki/notification/handler/FcmNotificationHandler.java
Labels: jira, backend

#46 [AH-38] 캠퍼스의 Group을 조회하는 API 구현
  solsolhanhankki/src/main/java/com/alddeul/solsolhanhankki/campus/model/repository/PickupZoneRepository.java
  solsolhanhankki/src/main/java/com/alddeul/solsolhanhankki/campus/presentation/CampusController.java
  solsolhanhankki/src/main/java/com/alddeul/solsolhanhankki/campus/presentation/response/PickupZoneResponse.java
  solsolhanhankki/src/main/java/com/alddeul/solsolhanhankki/order/application/GroupService.java
  solsolhanhankki/src/main/java/com/alddeul/solsolhanhankki/order/application/OrderService.java
  solsolhanhankki/src/main/java/com/alddeul/solsolhanhankki/order/model/entity/Groups.java
  solsolhanhankki/src/main/java/com/alddeul/solsolhanhankki/order/model/repository/GroupRepository.java
  solsolhanhankki/src/main/java/com/alddeul/solsolhanhankki/order/presentation/GroupController.java
  solsolhanhankki/src/main/java/com/alddeul/solsolhanhankki/order/presentation/OrderController.java
  solsolhanhankki/src/main/java/com/alddeul/solsolhanhankki/order/presentation/request/GroupSummaryRequest.java
  solsolhanhankki/src/main/java/com/alddeul/solsolhanhankki/order/presentation/response/GroupSummaryResponse.java
  solsolhanhankki/src/main/java/com/alddeul/solsolhanhankki/order/presentation/response/OrderConfirmationResponse.java
  solsolhanhankki/src/main/java/com/alddeul/solsolhanhankki/order/presentation/response/OrderItemResponse.java
  solsolhanhankki/src/main/java/com/alddeul/solsolhanhankki/order/presentation/response/OrderPreviewResponse.java
Labels: backend

#64 feat(payment) : 결제페이지 리다이렉션을 위한 API 규격 동기화
  solsolhanhankki/src/main/java/com/alddeul/solsolhanhankki/order/infra/dto/PaymentRequest.java
  solsolhanhankki/src/main/java/com/alddeul/solsolhanhankki/order/infra/payment/FakePaymentGateway.java
  solsolhanhankki/src/main/resources/application-prod.yml
Labels: backend
